In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential


In [3]:
#Importing Input data
data_cohesion = np.load('Inputs/4ft_cohesion.npy')
data_cohesion = data_cohesion[0:16,:]
data_friction = np.load('Inputs/4ft_friction.npy')
data_friction = data_friction[0:16,:]
data_watertable = np.load('Inputs/4ft_water_table.npy')
data_watertable = np.squeeze(data_watertable)

In [4]:
#Importing output Data
data_depth = np.load('Targets/4ft_failure_depths.npy')

In [5]:
#Size
data_cohesion = np.transpose(data_cohesion)
data_friction = np.transpose(data_friction)
data_watertable = np.transpose(data_watertable)
data_watertable = np.squeeze(data_watertable)
data_depth = np.squeeze(data_depth)
print(np.shape(data_cohesion))
print(np.shape(data_friction))
print(np.shape(data_watertable))
print(np.shape(data_depth))
n_y = 25
n_x =33
n_sim = np.shape(data_cohesion)[0]
n_final_test = 107
n_remain = n_sim - n_final_test
m = np.shape(data_cohesion)[1]

(284107, 16)
(284107, 16)
(284107,)
(284107,)


In [6]:
data_arr= np.zeros((n_remain,2*m + 2))
data_arr[0:n_remain,0:m] = data_cohesion[0:n_remain,:]
data_arr[0:n_remain,m:2*m] = data_friction[0:n_remain,:]
data_arr[0:n_remain,2*m] = data_watertable[0:n_remain]
data_arr[0:n_remain,2*m+1] = data_depth[0:n_remain]


In [7]:
# Validation
data_val= np.zeros((n_final_test,2*m+2))
data_val[:,0:m] = data_cohesion[n_remain:n_sim,:]
data_val[:,m:2*m] = data_friction[n_remain:n_sim,:]
data_val[:,2*m] = data_watertable[n_remain:n_sim]
data_val[:,2*m+1] = data_depth[n_remain:n_sim]

In [8]:
data_x = data_arr[:,:-1]
data_y = data_arr[:,-1].reshape(-1,1)

In [9]:
# Spliting test and training
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.2, random_state = 42)

In [10]:
y_train

array([[0.6096],
       [1.3716],
       [0.6096],
       ...,
       [0.1524],
       [1.9812],
       [3.5052]])

In [11]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
y_train = sc.fit_transform(y_train)
y_test = sc.fit_transform(y_test)

In [12]:
ann1 = tf.keras.models.Sequential()

In [13]:
#Adding the input and first hidden layer, will be adding a dense layer
ann1.add(tf.keras.layers.Dense(units = 256,activation = 'relu'))
ann1.add(tf.keras.layers.Dense(units = 128,activation = 'relu'))
ann1.add(tf.keras.layers.Dense(units = 64, activation = 'relu'))
ann1.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))
ann1.add(tf.keras.layers.Dense(units = 4, activation = 'relu'))
#Output Layer
ann1.add(tf.keras.layers.Dense(units = 1, activation = 'linear'))

In [14]:
#compling ann
ann1.compile(optimizer = 'adam', loss = 'mean_squared_error',metrics = ['accuracy'] )

In [15]:
#traing the model
ann1.fit(x_train,y_train,batch_size = 64, epochs = 100)

Epoch 1/100
3550/3550 [==============================] - 20s 5ms/step - loss: 0.3148 - accuracy: 0.0000e+00
Epoch 2/100
3550/3550 [==============================] - 18s 5ms/step - loss: 0.2075 - accuracy: 0.0000e+00
Epoch 3/100
3550/3550 [==============================] - 18s 5ms/step - loss: 0.1717 - accuracy: 0.0000e+00
Epoch 4/100
3550/3550 [==============================] - 18s 5ms/step - loss: 0.1519 - accuracy: 0.0000e+00
Epoch 5/100
3550/3550 [==============================] - 17s 5ms/step - loss: 0.1396 - accuracy: 0.0000e+00
Epoch 6/100
3550/3550 [==============================] - 23s 6ms/step - loss: 0.1307 - accuracy: 0.0000e+00
Epoch 7/100
3550/3550 [==============================] - 27s 8ms/step - loss: 0.1227 - accuracy: 0.0000e+00
Epoch 8/100
3550/3550 [==============================] - 33s 9ms/step - loss: 0.1167 - accuracy: 0.0000e+00
Epoch 9/100
3550/3550 [==============================] - 33s 9ms/step - loss: 0.1091 - accuracy: 0.0000e+00
Epoch 10/100
3550/3550 [====

3550/3550 [==============================] - 15s 4ms/step - loss: 0.0361 - accuracy: 0.0000e+00
Epoch 77/100
3550/3550 [==============================] - 15s 4ms/step - loss: 0.0382 - accuracy: 0.0000e+00
Epoch 78/100
3550/3550 [==============================] - 15s 4ms/step - loss: 0.0361 - accuracy: 0.0000e+00
Epoch 79/100
3550/3550 [==============================] - 15s 4ms/step - loss: 0.0366 - accuracy: 0.0000e+00
Epoch 80/100
3550/3550 [==============================] - 15s 4ms/step - loss: 0.0376 - accuracy: 0.0000e+00
Epoch 81/100
3550/3550 [==============================] - 15s 4ms/step - loss: 0.0349 - accuracy: 0.0000e+00
Epoch 82/100
3550/3550 [==============================] - 15s 4ms/step - loss: 0.0360 - accuracy: 0.0000e+00
Epoch 83/100
3550/3550 [==============================] - 15s 4ms/step - loss: 0.0366 - accuracy: 0.0000e+00
Epoch 84/100
3550/3550 [==============================] - 15s 4ms/step - loss: 0.0347 - accuracy: 0.0000e+00
Epoch 85/100
3550/3550 [========

In [16]:
y_pred = ann1.predict(x_test)

1775/1775 [==============================] - 2s 1ms/step


In [17]:
y_pred = sc.inverse_transform(y_pred)


In [18]:
y_pred

array([[1.0204287],
       [0.6135429],
       [2.2512488],
       ...,
       [1.5992073],
       [1.0062838],
       [1.8433905]], dtype=float32)

In [19]:
y_actual = sc.inverse_transform(y_test)

In [20]:
y_actual

array([[1.0668],
       [0.6096],
       [2.5908],
       ...,
       [1.3716],
       [1.0668],
       [1.9812]])

In [21]:
from sklearn.metrics import r2_score
r2 = r2_score(y_actual,y_pred)
r2

0.8832126188440386

In [22]:
x_val  = data_val[:,:-1]
x_val = sc.fit_transform(x_val)
y_val = data_val[:,-1].reshape(-1,1)
y_pred_val = ann1.predict(x_val)

4/4 [==============================] - 0s 5ms/step


In [23]:
y_val = sc.fit_transform(y_val)
np.shape(y_val)

(107, 1)

In [24]:
np.shape(y_val)

(107, 1)

In [25]:
from sklearn.metrics import r2_score
r2_val = r2_score(y_val,y_pred_val)
r2_val

0.7775432184051144

In [26]:
df = pd.DataFrame({"depth": data_depth})

In [27]:
print(np.unique(df[['depth']].values))

[0.     0.1524 0.3048 0.4572 0.6096 0.762  0.9144 1.0668 1.2192 1.3716
 1.524  1.6764 1.8288 1.9812 2.1336 2.286  2.4384 2.5908 2.7432 2.8956
 3.048  3.2004 3.3528 3.5052]


In [28]:
ann1.save("ann_depth_without_poly.h5")