In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential


In [2]:
#Importing Input data
data_cohesion = np.load('Inputs/4ft_cohesion.npy')
data_cohesion = data_cohesion[0:16,:]
data_friction = np.load('Inputs/4ft_friction.npy')
data_friction = data_friction[0:16,:]
data_watertable = np.load('Inputs/4ft_water_table.npy')
data_watertable = np.squeeze(data_watertable)

In [3]:
#Importing output Data
data_bearning = np.load('Targets/4ft_bearing_capacity.npy')

In [4]:
#Size
data_cohesion = np.transpose(data_cohesion)
data_friction = np.transpose(data_friction)
data_watertable = np.transpose(data_watertable)
data_watertable = np.squeeze(data_watertable)
print(np.shape(data_cohesion))
print(np.shape(data_friction))
print(np.shape(data_watertable))
print(np.shape(data_bearning))
n_y = 25
n_x =33
n_sim = np.shape(data_cohesion)[0]
n_final_test = 107
n_remain = n_sim - n_final_test
m = np.shape(data_cohesion)[1]

(284107, 16)
(284107, 16)
(284107,)
(284107,)


In [5]:
data_arr= np.zeros((n_remain,2*m + 2))
data_arr[0:n_remain,0:m] = data_cohesion[0:n_remain,:]
data_arr[0:n_remain,m:2*m] = data_friction[0:n_remain,:]
data_arr[0:n_remain,2*m] = data_watertable[0:n_remain]
data_arr[0:n_remain,2*m+1] = data_bearning[0:n_remain]


In [6]:
# Validation
data_val= np.zeros((n_final_test,2*m+2))
data_val[:,0:m] = data_cohesion[n_remain:n_sim,:]
data_val[:,m:2*m] = data_friction[n_remain:n_sim,:]
data_val[:,2*m] = data_watertable[n_remain:n_sim]
data_val[:,2*m+1] = data_bearning[n_remain:n_sim]

In [7]:
data_x = data_arr[:,:-1]
data_y = data_arr[:,-1].reshape(-1,1)

In [8]:
# Spliting test and training
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.2, random_state = 42)

In [9]:
y_train

array([[ 570468.7982592 ],
       [1555472.06480088],
       [ 195230.32009017],
       ...,
       [  68935.46117079],
       [ 431434.44040234],
       [ 283381.16806185]])

In [10]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)
y_train = sc.fit_transform(y_train)
y_test = sc.fit_transform(y_test)

In [11]:
ann1 = tf.keras.models.Sequential()

In [12]:
#Adding the input and first hidden layer, will be adding a dense layer
ann1.add(tf.keras.layers.Dense(units = 256,activation = 'relu'))
ann1.add(tf.keras.layers.Dense(units = 64, activation = 'relu'))
ann1.add(tf.keras.layers.Dense(units = 32, activation = 'relu'))
ann1.add(tf.keras.layers.Dense(units = 4, activation = 'relu'))
#Output Layer
ann1.add(tf.keras.layers.Dense(units = 1, activation = 'linear'))

In [13]:
#compling ann
ann1.compile(optimizer = 'adam', loss = 'mean_squared_error',metrics = ['accuracy'] )

In [14]:
#traing the model
ann1.fit(x_train,y_train,batch_size = 128, epochs = 100)

Epoch 1/100
1775/1775 [==============================] - 17s 8ms/step - loss: 0.0709 - accuracy: 0.0000e+00
Epoch 2/100
1775/1775 [==============================] - 14s 8ms/step - loss: 0.0232 - accuracy: 0.0000e+00
Epoch 3/100
1775/1775 [==============================] - 15s 8ms/step - loss: 0.0157 - accuracy: 0.0000e+00
Epoch 4/100
1775/1775 [==============================] - 14s 8ms/step - loss: 0.0119 - accuracy: 0.0000e+00
Epoch 5/100
1775/1775 [==============================] - 14s 8ms/step - loss: 0.0097 - accuracy: 0.0000e+00
Epoch 6/100
1775/1775 [==============================] - 14s 8ms/step - loss: 0.0082 - accuracy: 0.0000e+00
Epoch 7/100
1775/1775 [==============================] - 15s 8ms/step - loss: 0.0073 - accuracy: 0.0000e+00
Epoch 8/100
1775/1775 [==============================] - 14s 8ms/step - loss: 0.0065 - accuracy: 0.0000e+00
Epoch 9/100
1775/1775 [==============================] - 14s 8ms/step - loss: 0.0060 - accuracy: 0.0000e+00
Epoch 10/100
1775/1775 [====

1775/1775 [==============================] - 9s 5ms/step - loss: 0.0024 - accuracy: 0.0000e+00
Epoch 77/100
1775/1775 [==============================] - 10s 6ms/step - loss: 0.0024 - accuracy: 0.0000e+00
Epoch 78/100
1775/1775 [==============================] - 10s 6ms/step - loss: 0.0024 - accuracy: 0.0000e+00
Epoch 79/100
1775/1775 [==============================] - 10s 6ms/step - loss: 0.0024 - accuracy: 0.0000e+00
Epoch 80/100
1775/1775 [==============================] - 10s 5ms/step - loss: 0.0024 - accuracy: 0.0000e+00
Epoch 81/100
1775/1775 [==============================] - 10s 5ms/step - loss: 0.0023 - accuracy: 0.0000e+00
Epoch 82/100
1775/1775 [==============================] - 10s 5ms/step - loss: 0.0023 - accuracy: 0.0000e+00
Epoch 83/100
1775/1775 [==============================] - 9s 5ms/step - loss: 0.0023 - accuracy: 0.0000e+00
Epoch 84/100
1775/1775 [==============================] - 9s 5ms/step - loss: 0.0023 - accuracy: 0.0000e+00
Epoch 85/100
1775/1775 [===========

In [15]:
y_pred = ann1.predict(x_test)

1775/1775 [==============================] - 3s 2ms/step


In [16]:
y_pred = sc.inverse_transform(y_pred)


In [17]:
y_pred

array([[ 526298.5 ],
       [ 694447.06],
       [1437403.4 ],
       ...,
       [1142217.1 ],
       [ 403472.8 ],
       [ 890954.25]], dtype=float32)

In [18]:
y_actual = sc.inverse_transform(y_test)

In [19]:
y_actual

array([[ 556107.6384464 ],
       [ 675475.78921502],
       [1414716.44999281],
       ...,
       [1167433.62285317],
       [ 400579.32270175],
       [ 922156.1406706 ]])

In [20]:
from sklearn.metrics import r2_score
r2 = r2_score(y_actual,y_pred)
r2

0.9972315669936507

In [21]:
x_val  = data_val[:,:-1]
x_val = sc.fit_transform(x_val)
y_val = data_val[:,-1].reshape(-1,1)
y_pred_val = ann1.predict(x_val)

4/4 [==============================] - 0s 0s/step


In [22]:
y_val = sc.fit_transform(y_val)
np.shape(y_val)

(107, 1)

In [23]:
np.shape(y_val)

(107, 1)

In [24]:
from sklearn.metrics import r2_score
r2_val = r2_score(y_val,y_pred_val)
r2_val

0.9857757977517083

In [25]:
ann1.save("ann_bearing_without_poly.h5")